book/urls.py
from django.conf.urls.defaults import patterns, url
from models import  User
from django.conf import settings
from views import BookList
import views

urlpatterns = patterns('',
                       url(r'^$',BookList.as_view()),
                       url(r'^new/$',views.new,name="new_book"),
                       url(r'^search/$',views.book_search,name="book_search"),  
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'book_renting.views.home', name='home'),
    # url(r'^book_renting/', include('book_renting.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^books/', include('book.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', 
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'^accounts/login/$',  'book_renting.views.login'),
    url(r'^accounts/auth/$',  'book_renting.views.auth_view'), 

)

book/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Book(models.Model):
    STATUS =(('new','new'),('used','used'),('very_old','very_old'))
    title = models.CharField(max_length=50)
    isbn =models.IntegerField(max_length=13,unique=True)
    author_name = models.CharField(max_length=20)
    edition_number = models.IntegerField(max_length=13)
    publication_date = models.DateField()
    status = models.CharField(max_length=10,choices=STATUS)
    fees=models.DecimalField(max_digits=6, decimal_places=2)
    link = models.URLField()
    renter = models.ForeignKey(User)

    def __unicode__(self):
        return self.title  

book/forms.py
from django import forms 
from models import Book


class BookForm(forms.ModelForm):
    
    class Meta:
        model=Book
        fields = ('title', 'isbn','author_name','edition_number',
        		'publication_date','status','fees','link')

book/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import auth
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.template.context import RequestContext
from django.views.generic import ListView
from models import Book
from forms import BookForm
from django.db.models import Q

class BookList(ListView):
    model = Book
    template_name='books.html'

@login_required
@csrf_exempt
def new(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            book = form.save(commit=False)
            book.renter = request.user
            book.save()
            return HttpResponseRedirect('/books')
    else:
        form = BookForm()
    return render_to_response('new.html', {'form': form},context_instance=RequestContext(request))

def book_search(request):
    #import pdb;pdb.set_trace()
    if request.is_ajax():
        qe = request.GET.get( 'q' )
        if qe is not None:
            if qe.isdigit():
                results = Book.objects.filter(Q(isbn__exact=int(qe)))
            else:     
                results = Book.objects.filter(Q(title__icontains=qe) | Q(author_name__icontains=qe)) 
            return render_to_response( 'results.html',{'results': results })        

views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import auth
from django.views.decorators.csrf import csrf_exempt
from django.template.context import RequestContext
from django.views.generic import ListView

@csrf_exempt
def login(request):  
    return render_to_response('login.html',context_instance=RequestContext(request))

@csrf_exempt    
def auth_view(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
    
    if user is not None:
        auth.login(request, user)
        return HttpResponseRedirect('/books')
    else:
        return render_to_response('login.html',{'error':'wrong username or password'},context_instance=RequestContext(request))

templates/base.html
<html>

	<head>
			<title>{%block title %}BOOKS{% endblock %}</title>
			<link rel="stylesheet" type="text/css" media="all" href="{{ MEDIA_URL }}css/style.css" />
			<link rel="stylesheet" type="text/css" media="all" href="{{ MEDIA_URL }}css/livevalidation.css" />
						
	</head>
		
	<body>
		{% block main %}{% endblock %}
		<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.js"></script>
		<script type="text/javascript" src="{{ MEDIA_URL }}js/livevalidation.js"></script>
		{% block extra_js %}{% endblock %}	
	</body>
	
</html>

templates/books.html
{% extends "base.html"%}
{% block title %}BooksList| {{ block.super }}{% endblock %}
	
{% block main %}

	
		<form action="{% url 'new_book' %}">
			<input type="submit" value="add Book">
		</form>	

		<div>
			<input id="q" type="text" placeholder="title ,isbn or author name"/>
			<input id="searchSubmit" type="submit" value="Search"/> <br/> <br/>
		</div>
		
		<table id="books_table" border="1" width="70%">

			<tr> 
				<td width="40%"> Title </td>
				<td width="15%" > isbn</td> 
				<td width="15%"> author_name</td>
			</tr>
			
			<tr>
				{% for book in book_list %}
				<td>{{ book.title }}</td>
				<td>{{ book.isbn }}</td>
				<td>{{ book.author_name }}</td>
			</tr>
	        	{% endfor %}

		</table> 
 
		<div id="results"></div>
		 	
{% endblock %}


{% block extra_js %}

<script type="text/javascript">
	$( document ).ready( function() {
		$( '#searchSubmit' ).click( function() {
			q = $( '#q' ).val();
			
			$( '#results' ).load( '{% url 'book_search' %}?q=' + q );
		});
		
	var mysearch = new LiveValidation("q");
	mysearch.add( Validate.Presence, 
              { failureMessage: "Don't just ignore me, I wanna be your friend!" } );
	});
	
	$( document ).ajaxStart( function() {
		$('#books_table').hide(); 
	}).ajaxStop( function() {
 		$('#books_table').hide();
	});
	
	
	
</script>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block main %}

    <p class="error">{{ error }}

  <form action="/accounts/auth/" method="post">
    <label for="username">User name:</label>
    <input type="text" name="username" value="" id="username">
    <label for="password">Password:</label>
    <input type="password" name="password" value="" id="password">

    <input type="submit" value="login" />
    
  </form>

{% endblock %}

templates/new.html
{% extends "base.html"%}

{% block main %}

	{%if form.initial %}
		<h1>Edit Book</h1>
	{% else %}
		<h1>Add Book</h1>
	{% endif %}
		
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
    
{% endblock %}


{% block extra_js %}

<script type="text/javascript">
	$( document ).ready( function() {
var r = new LiveValidation( 'id_name', {onlyOnSubmit: true } );
r.add( Validate.Presence, 
              { failureMessage: "Don't just ignore me, I wanna be your friend!" } );

 });

</script>
{% endblock %}	

templates/results.html
{% if results|length %}
	<table>
	<tr class='even'>
		<td colspan="3" class="right">
		<strong>Found {{ results|length }} Books</strong>
		</td>
	</tr>
	{% for book in results %}
	<tr>
		<td><strong>{{ forloop.counter }}.</strong></td>
		<td>
		{{ book.title }} | {{ book.status }}<br/>
		<span class="hint">{{ book.author_name}}</span>
		</td>
	</tr>
	{% endfor %}
	</table>
{% else %}
	<div class="note">
	Your search yielded no results
	</div>
{% endif %}